---
title: "TD_analyses"
author: "Ziwei Zhang"
date: "2/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lme4)
library(ggeffects)
library(ggplot2)
library(tidyr)
library(lmerTest)
library(sjstats)
library(rstatix)
library(afex)
library(emmeans)
library(fitdistrplus)
```

```{r}
df_ordered <- read.csv('/Users/ziweizhang/Downloads/Stats_lr_trig_data/analysis_output/E2/TD_lmm_E2.csv')%>%
      mutate(participant = as.factor(participant),
           attention_state = as.factor(attention_state),
           within_triplet_counter = as.factor(within_triplet_counter),
           within_stream_position = as.factor(within_stream_position))

contrasts(df_ordered$within_triplet_counter) <- contr.treatment(base = 2, n = 3)
contrasts(df_ordered$within_stream_position) <- contr.treatment(base = 4, n = 6)

TD_fast <- df_ordered %>% subset(attention_state == 'fast')
TD_slow <- df_ordered %>% subset(attention_state == 'slow')

nan_se <- function(x) sqrt(var(x,na.rm=TRUE) / length(na.omit(x)))
nan_mean <- function(x) mean(na.omit(x))
```


# Main analyses

## Build mixed effects models
```{r}
model_1 = lmer(TD_rt ~ within_triplet_counter * attention_state + (1 | participant), data=df_ordered)
Anova(model_1)
```

```{r}
model_2 = lmer(TD_rt ~ within_triplet_counter * attention_state + (within_triplet_counter | participant), data=df_ordered)
Anova(model_2)
```

```{r}
model_3 = lmer(TD_rt ~ within_triplet_counter * attention_state + (attention_state | participant), data=df_ordered)
Anova(model_3)
```

```{r}
model_4 = lmer(TD_rt ~ within_triplet_counter * attention_state + (attention_state + within_triplet_counter|participant), data=df_ordered)
Anova(model_4)
```


```{r}
# model comparison
anova(model_1, model_2, model_3,model_4)
AIC(model_1, model_2, model_3,model_4)
```

```{r}
(em.test <- emmeans(model_4, list(pairwise ~ within_triplet_counter * attention_state) , transform = "response", adjust = "tukey"))
```


## Residual analyses
```{r}
#regress out the effect of shape position in the stream
model_residual_from_stream = lmer(TD_rt ~ within_stream_position + (1 | participant), data=df_ordered)
df_ordered$resid_from_stream<-resid(model_residual_from_stream)
```

```{r}
contrasts(df_ordered$within_triplet_counter) <- contr.treatment(base = 2, n = 3)
model_5 = lmer(resid_from_stream ~ within_triplet_counter * attention_state + (attention_state + within_triplet_counter|participant), data=df_ordered)

summary(model_5)
Anova(model_5)
chi_sqrt_E1a <- Anova(model_5)[3,'Chisq']
chi_sqrt_E1a
```


```{r}
se <- function(x) sqrt(var(x) / length(x))
nan_mean <- function(x) mean(na.omit(x))
df.summary <- df_ordered %>%
  group_by(attention_state,within_triplet_counter) %>%
  dplyr::summarise(
    se_resid = se(resid_from_stream),
    mean_resid = mean(resid_from_stream),
    se_rt = se(TD_rt),
    mean_rt = mean(TD_rt)
  )
df.summary <- na.omit(df.summary)

df.summary$attention_state <- factor(df.summary$attention_state, 
                      levels = c("slow", "fast"))
```

```{r}
p1 <- ggplot(df.summary, aes(within_triplet_counter, mean_rt, ymin = mean_rt-se_rt, ymax = mean_rt+se_rt, group=attention_state)) +
  geom_line(aes(color=attention_state),size=1.2) +
  geom_pointrange(aes(color=attention_state)) +
  geom_errorbar(aes(color=attention_state), width = 0.06) +
  scale_color_manual(values=c("#508f22","#682191"), labels = c("high attentional state","low attentional state")) +
  theme_classic() + theme(aspect.ratio = 0.8,legend.position="top", axis.text.y=element_text(size=10, colour="black"), axis.text.x=element_text(size=10, colour="black"),axis.title.y=element_text(size=10),axis.title.x=element_text(size=10),legend.direction = "vertical", legend.text=element_text(size=10)) +
  labs(x = " ", y = "RT (ms)", color = "") +
  scale_x_discrete(expand = c(0,0.2),breaks=c("1","2","3"),labels=c("first \n triplet position", "second \n triplet position", "third \n triplet position")) +
  ylim(360,420) 
#, plot.tag = element_text(hjust=0.5, vjust=0.5, size=18),plot.tag.position = "topleft"

#ggsave("Fig3a.png", width = 5.5, height = 4, dpi=300)
p1
```

```{r}
p2 <- ggplot(df.summary, aes(within_triplet_counter, mean_resid, ymin = mean_resid-se_resid, ymax = mean_resid+se_resid, group=attention_state)) +
  geom_line(aes(color = attention_state),size=1.2) +
  geom_pointrange(aes(color = attention_state)) +
  geom_errorbar(aes(color= attention_state), width = 0.06)+
  scale_color_manual(values=c("#508f22","#682191"), labels = c("high attentional state","low attentional state")) +
  theme_classic() + theme(aspect.ratio = 0.8,legend.position="top", axis.text.y=element_text(size=10, colour="black"), axis.text.x=element_text(size=10, colour="black"),axis.title.y=element_text(size=10),axis.title.x=element_text(size=10),legend.direction = "vertical", legend.text=element_text(size=10)) +
  labs(x = " ", y = "residual", color = "") +
  scale_x_discrete(expand = c(0,0.2),breaks=c("1","2","3"),labels=c("first \n triplet position", "second \n triplet position", "third \n triplet position")) +
  ylim(-20,20) 
#ggsave("Fig3c.png", width = 5.5, height = 4, dpi=300)

p2
```


## RT distribution:
https://rpubs.com/eraldagjika/715261
```{r}
(nan_mean(df_ordered$TD_rt))
(sd(df_ordered$TD_rt, na.rm = TRUE))
```


```{r}
p_supp_1 <- ggplot(df_ordered,aes(x=TD_rt)) +
    geom_histogram(alpha=0.7, bins = 30, color="#B4B4B4", fill="light gray") +
    theme_classic() + theme(aspect.ratio = 0.8, legend.position="right", axis.text.y=element_text(size=14), axis.text.x=element_text(size=14,colour = "black"), axis.title.y=element_text(size=14,colour = "black"),axis.title.x=element_text(size=14), legend.direction = "vertical", legend.text=element_text(size=14)) +
    guides(fill = guide_legend(label.position = "top")) +
  labs(x = "E1 TD RT(ms)", y = "count", fill = "") +
  ylim(0,1383) + xlim(-33.54375, 1643.64375) +
  scale_y_continuous(limits = c(0,1383), breaks = seq(0,1383, by = 250))


#ggsave("SuppFig_5a.pdf", width = 5.5, height = 4, dpi=300)
p_supp_1
```

```{r}
normal_dist <- fitdistrplus::fitdist(df_ordered$TD_rt, "norm")
plot(normal_dist)

lognorm_dist <- fitdistrplus::fitdist(df_ordered$TD_rt, "lnorm")
plot(lognorm_dist)

gamma_dist <- fitdistrplus::fitdist(df_ordered$TD_rt, "gamma")
plot(gamma_dist)

gofstat(list(gamma_dist, normal_dist,lognorm_dist), fitnames = c("gamma", "norm","lnorm"))
```

Fit the distribution of the data to determine best family for mixed effects model
```{r Compare fits to RT data, eval=FALSE, warning=FALSE, include=FALSE}
gamma_dist <- fitdistrplus::fitdist(df_ordered$TD_rt, "gamma")
normal_dist <- fitdistrplus::fitdist(df_ordered$TD_rt, "norm")
summary(gamma_dist)
summary(normal_dist)

par(mfrow=c(2,2))
plot.legend <- c("gamma", "norm")
denscomp(list(gamma_dist, normal_dist), legendtext = plot.legend)
cdfcomp (list(gamma_dist, normal_dist), legendtext = plot.legend)
qqcomp  (list(gamma_dist, normal_dist), legendtext = plot.legend)
ppcomp  (list(gamma_dist, normal_dist), legendtext = plot.legend)

```


```{r}
norm_dist <-  fitdistrplus::fitdist(df_ordered$TD_rt, "norm")
#pdf(file="SuppFig_6.pdf") #, width = 5.5, height = 4, dpi=300
plot(norm_dist)
dev.off()
```


## Separate models for each attentional state
### Low attention
```{r}
model_fast = lmer(TD_rt ~ within_triplet_counter + (within_triplet_counter|participant), data=TD_fast)
Anova(model_fast)
anova(model_fast)

(em.test <- emmeans(model_fast, specs = pairwise ~ within_triplet_counter, transform = "response"))
```

### High attention
```{r}
model_slow = lmer(TD_rt ~ within_triplet_counter + (within_triplet_counter|participant), data=TD_slow)
Anova(model_slow)
(em.test <- emmeans(model_slow, specs = pairwise ~ within_triplet_counter, transform = "response"))
```


## Obtain RT facilitation for individual analyses

```{r}
#detach("package:plyr")

TD_fast_sub <- TD_fast %>%
  group_by(participant, attention_state,within_triplet_counter) %>% summarise(mean_TD_rt = mean(TD_rt))
TD_fast_sub
```

```{r}
#TD_fast_sub[,TD_rt := balance - shift(balance,1), by = within_triplet_counter]

TD_fast_fac <- TD_fast_sub %>% group_by(attention_state, participant) %>% 
  mutate(fast_fac_13 = -(mean_TD_rt - lag(mean_TD_rt,2)),
         fast_fac_12_23 = -(mean_TD_rt - lag(mean_TD_rt,1)),
         )
TD_fast_fac
```

```{r}
TD_fast_fac_clean <- TD_fast_fac[TD_fast_fac$within_triplet_counter == 3, c(1,5)]
TD_fast_fac_clean$fast_fac_12 <- subset(TD_fast_fac, within_triplet_counter == '2' )$fast_fac_12_23
TD_fast_fac_clean$fast_fac_23 <- subset(TD_fast_fac, within_triplet_counter == '3' )$fast_fac_12_23
TD_fast_fac_clean
```

```{r}
TD_slow_sub <- TD_slow %>%
  group_by(participant, attention_state,within_triplet_counter) %>% summarise(mean_TD_rt = mean(TD_rt))
TD_slow_sub
```


```{r}
TD_slow_fac <- TD_slow_sub %>% group_by(attention_state, participant) %>% 
  mutate(slow_fac_13 = -(mean_TD_rt - lag(mean_TD_rt,2)),
         slow_fac_12_23 = -(mean_TD_rt - lag(mean_TD_rt,1)),
         )
TD_slow_fac
```

```{r}
TD_slow_fac_clean <- TD_slow_fac[TD_slow_fac$within_triplet_counter == 1, c(1,5)]
#include_sub <- unique(TD_slow_fac_clean$participant)

slow_fac_12 <- TD_slow_fac[TD_slow_fac$within_triplet_counter == '2', c(1,6)]
names(slow_fac_12)[2] <- 'slow_fac_12'
slow_fac_12
```

```{r}
slow_fac_23 <- TD_slow_fac[TD_slow_fac$within_triplet_counter == '3',c(1,5,6)]
  #subset(TD_slow_fac, within_triplet_counter == '3' )$slow_fac_12_23
names(slow_fac_23)[3] <- 'slow_fac_23'
slow_fac_23
```


```{r}
TD_slow_fac_clean <- merge(slow_fac_12, slow_fac_23, by = "participant", all.x=TRUE, all.y=TRUE)
```


```{r}
TD_sub <- df_ordered %>%
  group_by(participant, within_triplet_counter) %>% summarise(mean_TD_rt = mean(TD_rt))
TD_sub
```


```{r}
TD_fac <- TD_sub %>% group_by(participant) %>% 
  mutate(overall_fac_13 = -(mean_TD_rt - lag(mean_TD_rt,2)),
         overall_fac_12_23 = -(mean_TD_rt - lag(mean_TD_rt,1)),
         )
TD_fac
```

```{r}
TD_fac_clean <- TD_fac[TD_fac$within_triplet_counter == 3, c(1,4)]
TD_fac_clean$overall_fac_12 <- subset(TD_fac, within_triplet_counter == '2' )$overall_fac_12_23
TD_fac_clean$overall_fac_23 <- subset(TD_fac, within_triplet_counter == '3' )$overall_fac_12_23
TD_fac_clean
```


```{r}
TD_fac_clean_bystate <- merge(TD_fast_fac_clean, TD_slow_fac_clean, by = "participant", all.x=TRUE, all.y=TRUE)
TD_fac_clean <- merge(TD_fac_clean_bystate, TD_fac_clean, by = "participant", all.x=TRUE, all.y=TRUE)
TD_fac_clean
```

```{r}
#write.csv(x=TD_fac_clean, file="TD_fac_clean.csv")
```





